{% set PKG_NAME = 'nadamq' %}
{% set MODULE_NAME = 'nadamq' %}
{% set LIB_NAME = 'NadaMQ' %}
package:
  name: {{ PKG_NAME }}
  version: 0.20.5

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 0
  script:
    # Create Cpp files and copy Arduino library files to Conda Arduino library.
    - make clean
    - make install

requirements:
  build:
    - python {{ python }}
    - ragel # [win]
    - ntfsutils # [win]
    - libpython # [win]
    - msinttypes  # [win and py2k]
    - versioneer
    - pint
    - numpy
    - cmake
    - make
    - cython
    - pyserialy
    - or-event
    - path-helpers
    - platformio-helpers
    - dropbot-headers
    - scons
    - pip

outputs:
  - name: {{ PKG_NAME }}-dev
    noarch: generic
    files:
      - share
    requirements:
      run:
        - dropbot-headers
  - name: {{ PKG_NAME }}
    platform: {{ target_platform }}
    files:
      - {{ SP_DIR }}/{{ MODULE_NAME }}
    requirements:
      run:
        - python >=3.6
        - {{ pin_subpackage(PKG_NAME + '-dev', max_pin='x.x') }}
        - pint
        - numpy
        - pyserial
        - or-event
        - path-helpers
        - scons
        - ntfsutils # [win]
        - platformio-helpers

    test:
      imports:
        - {{ MODULE_NAME }}
        - {{ MODULE_NAME }}.{{ LIB_NAME }}

about:
  home: https://github.com/sci-bots/{{ PKG_NAME }}
  license: GPL
  summary: Embedded-friendly transport layer, inspired by ZeroMQ.

  # source will be downloaded prior to filling in jinja templates
# Example assumes that this folder has setup.py in it
source:
  path: ..
#  git_url: ../
